-- Create database
CREATE DATABASE IF NOT EXISTS sinhvien CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE sinhvien;

-- Create tables
CREATE TABLE IF NOT EXISTS TRUONG (
    MaTruong VARCHAR(20) PRIMARY KEY,
    TenTruong VARCHAR(100),
    DiaChi VARCHAR(200),
    SoDT VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS NGANH (
    MaNganh VARCHAR(20) PRIMARY KEY,
    TenNganh VARCHAR(100),
    LoaiNganh VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS SINHVIEN (
    SoCMND VARCHAR(20) PRIMARY KEY,
    HoTen VARCHAR(100),
    Email VARCHAR(100),
    SoDT VARCHAR(15),
    DiaChi VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS TOT_NGHIEP (
    SoCMND VARCHAR(20),
    MaTruong VARCHAR(20),
    MaNganh VARCHAR(20),
    HeTN VARCHAR(50),
    NgayTN DATE,
    LoaiTN VARCHAR(50),
    PRIMARY KEY (SoCMND, MaTruong, MaNganh),
    FOREIGN KEY (SoCMND) REFERENCES SINHVIEN(SoCMND),
    FOREIGN KEY (MaTruong) REFERENCES TRUONG(MaTruong),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
);

CREATE TABLE IF NOT EXISTS CONG_VIEC (
    SoCMND VARCHAR(20),
    NgayVaoCongTy DATE,
    MaNganh VARCHAR(20),
    TenCongTy VARCHAR(100),
    DiaChiCongTy VARCHAR(200),
    ThoiGianLamViec INT,
    PRIMARY KEY (SoCMND, NgayVaoCongTy),
    FOREIGN KEY (SoCMND) REFERENCES SINHVIEN(SoCMND),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
);
